name:                ghc-example
version:             0.1.0.0
license:             BSD3

description:         Please see the README on GitHub

dependencies:
- base
- ghc
- ghc-paths


executables:
  ghc-example:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


